version: '3'

services:
  web:
    build: .
    container_name: nextjs-app
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    depends_on:
      - web

volumes:
  certs:
  certs-data: