name: Continuous Deployment

on:
  push: # Trigger CD only when a merge happens to main
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Check out repository
          uses: actions/checkout@v2

        - name: Set up SSH
          uses: webfactory/ssh-agent@v0.5.3
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
        - name: Deploy to server
          env:
            PASSWORD: ${{ secrets.SSH_PASSWORD }}
          run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
              cd /home/django-personal-website-app/blog
              git pull origin main
              pipenv install --deploy --ignore-pipfile
              pipenv run python personal_website/manage.py migrate
              pipenv run python personal_website/manage.py collectstatic --noinput
            EOF

        - name: Restart services
          env:
            PASSWORD: ${{ secrets.SSH_PASSWORD }}
          run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
            "echo \"$PASSWORD\" | sudo -S systemctl restart gunicorn && \
             echo \"$PASSWORD\" | sudo -S systemctl restart nginx"
